import { Activity } from "./types";

export const initialActivities: Activity[] = [
  {
    name: "Global AI Hackathon 2026",
    activityType: "Hackathon(External)-Win",
    description: "24-hour coding challenge focused on AI-powered solutions for real-world problems",
    organization: "Coding Society",
    tokens: 6,
    startDate: "Apr 28, 2026",
    endDate: "May 2, 2026",
    progress: 40,
    status: "In Progress",
  },
  {
    name: "Introduction to Machine Learning",
    activityType: "NPTEL-Elite+Gold",
    description: "Premium NPTEL course covering core ML concepts and model deployment",
    organization: "NPTEL",
    tokens: 4,
    startDate: "Mar 1, 2026",
    endDate: "Apr 10, 2026",
    progress: 80,
    status: "Pending AI Verification",
  },
  {
    name: "Startup & Entrepreneurship Seminar",
    activityType: "Other College Events",
    description: "Entrepreneurship, pitching, and business strategy sessions",
    organization: "Business Club",
    tokens: 3,
    startDate: "Mar 20, 2026",
    endDate: "Apr 5, 2026",
    progress: 100,
    status: "Awaiting Faculty Approval",
  },
  {
    name: "AWS Cloud Practitioner",
    activityType: "Certification-Global",
    description: "Global cloud certification covering AWS core services and architecture",
    organization: "Amazon Web Services",
    tokens: 6,
    startDate: "Feb 10, 2026",
    endDate: "Mar 30, 2026",
    progress: 100,
    status: "Rejected",
    feedback:
      "The uploaded certificate image is blurry and the validation ID is not visible. Please re-upload a clear copy.",
  },
  {
    name: "React Advanced Workshop",
    activityType: "Workshop",
    description: "Deep dive into advanced React patterns, hooks, and performance optimization",
    organization: "Tech Club",
    tokens: 2,
    startDate: "Jan 15, 2026",
    endDate: "Feb 20, 2026",
    progress: 100,
    status: "Completed",
  },
  {
    name: "NPTEL Python Programming",
    activityType: "NPTEL-Pass",
    description: "Foundational Python course with hands-on projects",
    organization: "NPTEL",
    tokens: 2,
    startDate: "Dec 1, 2025",
    endDate: "Jan 10, 2026",
    progress: 100,
    status: "Completed",
  },
];
